org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
minecraft_version=26.1
loader_version=0.19.5
loom_version=1.18.2
fabric_version=0.145.1+26.1
fabric_api_min_version=0.145.1
minecraft_supported_versions=>=26.1 <=26.3
mod_version=1.0.1
maven_group=io.github.adminvvv.lifelink
archives_base_name=lifelink
junit_version=5.11.4
mockito_version=5.23.0
